

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DSBDD
    ports:
      - "8889:8889"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: